# render.yaml — Minimal Streamlit web service
services:
  - type: web
    name: access-auditor
    env: python
    plan: free            # or 'starter'/'standard' if you need more
    region: oregon        # choose your region
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false       # set from Render dashboard if you want remediation plan
