services:
- type: web
name: access-auditor
runtime: python
plan: free
envVars:
- key: PYTHON_VERSION
value: 3.11.9
buildCommand: |
pip install -r requirements.txt
python -m playwright install --with-deps chromium
startCommand: |
streamlit run app.py --server.port $PORT --server.address 0.0.0.0
autoDeploy: true
