[server]
headless = true
address = "0.0.0.0"
# port is injected by Render via $PORT when you start the app
enableXsrfProtection = true
# Omit enableCORS entirely (defaults to true when XSRF is enabled)
