# ── .streamlit/config.toml ───────────────────────────────────────────────────
[server]
headless = true
enableXsrfProtection = true
enableCORS = false  # fronted by container/network; restrict via gateway if needed
maxUploadSize = 50

[theme]
primaryColor = "#003B73"
base = "light"

[browser]
gatherUsageStats = false
